apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-svc
  template:
    metadata:
      labels:
        app: fastapi-svc
    spec:
      containers:
      - name: fastapi
        image: my-fastapi-svc:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  namespace: default
spec:
  selector:
    app: fastapi-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
